[project]
name = "shadowrendering"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "glfw>=2.9.0",
    "moderngl>=5.12.0",
    "pyglm>=2.8.2",
    "pyobjloader>=0.0.7",
]
